language: go

go:
  - 1.11

addons:
  ssh_known_hosts: website.com

before_install:
  - bash _scripts/install.sh

script:
  - hugo -d public

deploy:
  provider: script
  script: bash _scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master

